import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:pluto_grid/pluto_grid.dart';

// 列の定義
List<PlutoColumn> columns = [
  PlutoColumn(
      title: '参加者',
      field: 'name',
      type: PlutoColumnType.text(),
      width: 190,
      frozen: PlutoColumnFrozen.start,
      enableContextMenu: false,
      enableDropToResize: false,
      enableColumnDrag: false,
      enableSorting: false,
      readOnly: true,
      backgroundColor: Colors.black.withOpacity(0.05)),
] +
    List.generate(
      16,
          (index) => PlutoColumn(
          title: '${index + 1}(${["土", "日", "月", "火", "水", "木", "金"][(index + 1) % 7]})',
          field: '${index + 1}',
          type: PlutoColumnType.text(),
          width: 100,
          enableContextMenu: false,
          enableDropToResize: false,
          enableColumnDrag: false,
          enableSorting: false,
          readOnly: true,
          textAlign: PlutoColumnTextAlign.center,
          titleTextAlign: PlutoColumnTextAlign.center,
          backgroundColor: Colors.black.withOpacity(0.05)),
    );

// 行の定義
List<PlutoRow> rows = [
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '参加'),
      '2': PlutoCell(value: '不参加'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: ''),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '片岡岩崎増田片岡２岩崎２増田２片岡３岩崎'),
      '1': PlutoCell(value: '〇'),
      '2': PlutoCell(value: '✕'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎山 拓郎助'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
];

class MyDataTable extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PlutoGrid(
      columns: columns,
      rows: rows,
      onLoaded: (PlutoGridOnLoadedEvent event) {
        // 必要に応じてグリッドをロードした後の処理を記述します
        debugPrint("Grid Loaded");
      },
      onChanged: (PlutoGridOnChangedEvent event) {
        // データが変更されたときの処理
        debugPrint("Cell changed: ${event.rowIdx}, ${event.column.field}, ${event.value}");
      },
      configuration: const PlutoGridConfiguration(
          style: PlutoGridStyleConfig(
            cellTextStyle: TextStyle(fontSize: 30),
            columnTextStyle: TextStyle(fontSize: 30),
            columnHeight: 150,
            rowHeight: 100,

          )),
    );
  }
}

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PlutoGrid Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('PlutoGrid Demo'),
        ),
        body: MyDataTable(),
      ),
    );
  }
}
