import 'package:pluto_grid/pluto_grid.dart';

List<PlutoRow> rows = [
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '参加'),
      '2': PlutoCell(value: '不参加'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: ''),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '片岡岩崎増田片岡２岩崎２増田２片岡３岩崎'),
      '1': PlutoCell(value: '〇'),
      '2': PlutoCell(value: '✕'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎山 拓郎助'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
  PlutoRow(
    cells: {
      'name': PlutoCell(value: '岩崎拓郎'),
      '1': PlutoCell(value: '○'),
      '2': PlutoCell(value: '○'),
      '3': PlutoCell(value: '○'),
      '4': PlutoCell(value: '○'),
      '5': PlutoCell(value: '○'),
      '6': PlutoCell(value: '○'),
      '7': PlutoCell(value: '○'),
      '8': PlutoCell(value: '○'),
      '9': PlutoCell(value: '○'),
      '10': PlutoCell(value: '○'),
      '11': PlutoCell(value: '○'),
      '12': PlutoCell(value: '○'),
      '13': PlutoCell(value: '○'),
      '14': PlutoCell(value: '○'),
      '15': PlutoCell(value: '○'),
      '16': PlutoCell(value: '○'),
    },
  ),
];